export const helplineData = [
  {
    service: "National Emergency Number",
    description: "National Emergency",
    number: "999",
    category: "All",
    image: "./assets/card-img/emergency.png",
  },
  {
    service: "Police Helpline Number",
    description: "Police",
    number: "999",
    category: "Police",
    image: "./assets/card-img/police.png",
  },
  {
    service: "Fire Service Number",
    description: "Fire Service",
    number: "999",
    category: "Fire",
    image: "./assets/card-img/fire-service.png",
  },
  {
    service: "Ambulance Service",
    description: "Ambulance",
    number: "1994-999999",
    category: "Health",
    image: "./assets/card-img/ambulance.png",
  },
  {
    service: "Women & Child Helpline",
    description: "Women & Child Helpline",
    number: "109",
    category: "Help",
    image: "./assets/card-img/emergency.png",
  },
  {
    service: "Anti-Corruption Helpline",
    description: "Anti-Corruption",
    number: "106",
    category: "Govt.",
    image: "./assets/card-img/emergency.png",
  },
  {
    service: "Electricity Helpline",
    description: "Electricity Outage",
    number: "16216",
    category: "Electricity",
    image: "./assets/card-img/emergency.png",
  },
  {
    service: "Brac Helpline",
    description: "Brac",
    number: "16445",
    category: "NGO",
    image: "./assets/card-img/brac.png",
  },
  {
    service: "Bangladesh Railway Helpline",
    description: "Bangladesh Railway",
    number: "163",
    category: "Travel",
    image: "./assets/card-img/Bangladesh-Railway.png",
  },
];
